---
name: fusioncatcher
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=2.7
  - biopython >=1.50
  - bowtie=1.2.3
  - fusioncatcher-seqtk=1.2
  - star=2.7.2b
  - bowtie2=2.3.5
  - bbmap=38.44
  - blat=35
  - lzo
  - bwa=0.7.12
  - ucsc-faToTwoBit
  - velvet=1.2.10
  - openpyxl=2.5.0a2
  - xlrd=1.0.0
  - pigz=2.3
  - samtools=0.1.19
  - picard=2.10.6
  - numpy=1.13.1
  - parallel=20171222
  - ucsc-liftover
  - oases
  - lzop
  - openjdk
  - sra-tools=2.9.6
  - zip
  - coreutils
  - grep
  - wget
